repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      # - id: check-toml # we have tomls with invalid syntax for tests
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: 'https://github.com/fredrikekre/runic-pre-commit'
    rev: v2.2.0
    hooks:
      - id: runic
        args: ["--inplace", "--diff", "--docstrings"]
        additional_dependencies:
          - 'Runic@1.7' # Keep version in sync with .github/workflows/Checks.yml
